### ISSUE TITLE
Check that latest version is being run

### ISSUE THREAD

**Issue by andreasnoack** [bcbi/CompatHelper.jl#183]
Assume three packages A, B, and C with the dependency structure
- A depends on B and C
- B depends on C.

Now, C makes a breaking release which triggers CompatHelper PRs to both A and B. However, package A wont actually be testing the new version of C since the dependency of B will hold it back to the previous version. We just got bitten by this where we accidentally merged a CompatHelper PR for Distributions 0.22 that didn’t actually test our package with version 0.22.

**Comment by ericphanson** [comment]
It seems like a reliable way to do this is to just have CompatHelper run the tests itself in an isolated environment and then open a PR when it works (and file an issue if it doesn't?). It doesn't have a release version yet, but @tkf's [Run.jl](https://github.com/tkf/Run.jl) provides some tooling for running tests like that I think.

**Comment by StefanKarpinski** [comment]
The package being tested should be added fixed at the version being tested. If that's not possible, there are bigger problems.

**Comment by ericphanson** [comment]
I think it's possible and is what's being discussed here-- but it's not what CompatHelper does. CompatHelper just makes a PR to broaden compat, without doing any testing itself, and you hope/check that your CI on the PR is testing the right version.

**Comment by tkf** [comment]
Unfortunately, I don't think Run.jl can help directly here. `Run.test` is just a bit more flexible about the test environment than `Pkg.test`.  So, you can check-in Manifest.toml if you use Run.jl and then it is easy to notice that the dependency in question is updated accordingly.  But I don't think it's a satisfying solution.

BTW, I think this issue is more or less a dup of #160.

**Comment by andreasnoack** [comment]
Yes. This is indeed covered by #160
