### ISSUE TITLE
CompatHelper.jl not working since 2 months

### ISSUE THREAD

**Issue by VEZY** [bcbi/CompatHelper.jl#201]
CompatHelper.jl was working very nicely since 2 months ago when it started to return an error. I think it is happening because of a `nothing` appearing here:
``` 
registries = Pkg.Types.RegistrySpec[Pkg.Types.RegistrySpec("General", UUID("23338594-aafe-5451-b93e-139f81909106"), "https://github.com/JuliaRegistries/General.git", nothing)];
```
I think from [here](https://github.com/bcbi/CompatHelper.jl/blob/c592cf93f8957a57649488da0c520554b1927d2e/src/update_manifests.jl#L60). 

See the error on Github action from my repo [here](https://github.com/VEZY/DynACof.jl/runs/663010942?check_suite_focus=true).

Can someone help me with this issue ? I tried so many things I don't know what to do anymore.

**Comment by DilumAluthge** [comment]
This issue has been resolved. For future readers, here is what we learned:

It turns out that the issue was one or more broken `Manifest.toml` files in the repository.

We removed all `Manifest.toml` files from the repository: https://github.com/VEZY/DynACof.jl/pull/3

After that, CompatHelper ran successfully. Here is an example run that was successful: https://github.com/VEZY/DynACof.jl/actions/runs/101743121

And here are three pull requests that were opened during this successful CompatHelper run:
1. https://github.com/VEZY/DynACof.jl/pull/5
2. https://github.com/VEZY/DynACof.jl/pull/6
3. https://github.com/VEZY/DynACof.jl/pull/7
