### ISSUE TITLE
Run Pkg.update on Manifest.toml files before PR

### ISSUE THREAD

**Issue by tkf** [bcbi/CompatHelper.jl#29]
When a package repository tracks in `test/Manifest.toml`, `docs/Manifest.toml`, `benchmark/Manifest.toml`, etc., those files must be updated for the CI to run against newly available upstream packages.  It would be great if CompatHelper.jl can automate this workflow as well.  Is it in the scope of CompatHelper.jl?

**Comment by DilumAluthge** [comment]
I’m not 100% sure I understand why this is necessary.

Why not check in `test/Project.toml` instead of `test/Manifest.toml`, `docs/Project.toml` instead of `docs/Manifest.toml`, and `benchmark/Project.toml` instead of `benchmark/Manifest.toml`.

And then, in those `Project.toml` files, either don’t have any compat entries, or if you do have compat entries, make them of the form `>= x.y.z`.

Then the `test`, `docs`, `benchmark` projects will automatically use the latest versions of their dependencies.

The only reason that the CompatHelper.jl bot is necessary is because we strongly recommend having upper-bounded compat entries in your package’s main `Project.toml` file. We don’t have a similar recommendation for the `test`, `docs`, `benchmark` projects, so I don’t think you needed upper-bounded compat entries in those projects.

**Comment by tkf** [comment]
You need to check in subproject manifests `{test,docs,benchmark}/Manifest.toml` if

* you are using non-registered packages as dependencies
* you want reproducible test, documentation build, and benchmarks

OK, technically, I can write a build script for each subproject to achieve those goals.  But it'd be great if I don't have to re-implement what Pkg already does.

**Comment by DilumAluthge** [comment]
I guess this is doable. CompatHelper would `cd` into the `docs` folder and run `julia --project -e 'import Pkg; Pkg.instantiate(); Pkg.update()'`. And then repeat that for all of the folders.

You would provide a vector `["test", "docs", "benchmark"]` to let me know which projects you want me to update.

**Comment by tkf** [comment]
That sounds great.  Or maybe even add another API `CompatHelper.main(precommit_hook)` so that I can just do

```yaml
run: |-
  julia -e '
  using CompatHelper
  CompatHelper.main() do
      run(`julia --project=test -e 'import Pkg; Pkg.instantiate(); Pkg.update()'`)
      run(`julia --project=docs -e 'import Pkg; Pkg.instantiate(); Pkg.update()'`)
  end
  '
```

and you can avoid dealing with similar feature requests?

**Comment by DilumAluthge** [comment]
Not a terrible idea

**Comment by DilumAluthge** [comment]
@tkf Can you try the feature out? You'll need to use the `da/precommit_hook` branch.

So you'd have to change the `Pkg.add` step in your `.github/workflows/CompatHelper.yml` file to something like this:
```julia
julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(name = "CompatHelper", url = "https://github.com/bcbi/CompatHelper.jl.git", rev = "da/precommit_hook"))'
```

**Comment by DilumAluthge** [comment]
@tkf It would be great to add a section to the README documenting the `precommit_hook` feature. Would you be willing to write up a brief explanation, along with the example YAML snippet? And make a PR?

**Comment by tkf** [comment]
I'll send a PR :+1:
